var station_map = {
    "RAN":"Rannoch",
    "SHB":"Shirebrook",
    "HFS":"Hatfield & Stainforth",
    "DIS":"Diss",
    "BKL":"Bickley",
    "COB":"Cooden Beach",
    "EDR":"Edmonton Green",
    "KBW":"Knebworth",
    "WTE":"Whitlocks End",
    "SOU":"Southampton Central",
    "NOT":"Nottingham",
    "GRN":"Grindleford",
    "NTA":"Newton Abbot",
    "FWY":"Five Ways",
    "GSW":"Garswood",
    "LER":"Leytonstone High Road",
    "TLB":"Talybont",
    "MIS":"Mistley",
    "TNA":"Thornton Abbey",
    "WGT":"Wigton",
    "WBL":"Warblington",
    "ENF":"Enfield Town",
    "WLM":"Williamwood",
    "BSE":"Bury St Edmunds",
    "SDR":"Saunderton",
    "WNN":"Wennington",
    "ISP":"Islip",
    "KEY":"Keyham",
    "GEA":"Gretna Green",
    "LEU":"Leuchars (For St. Andrews)",
    "SBU":"Southbury",
    "SWS":"South Wigston",
    "DAT":"Datchet",
    "HUD":"Huddersfield",
    "LIT":"Littlehampton",
    "WYT":"Wythall",
    "PBL":"Parbold",
    "HKH":"Hawkhead",
    "WOH":"Woldingham",
    "RIC":"Rickmansworth",
    "ESH":"Esher",
    "BCE":"Bracknell",
    "SAD":"Sandwell & Dudley",
    "KSW":"Kirkby Stephen",
    "SIL":"Sileby",
    "RAV":"Ravenglass For Eskdale",
    "SPK":"Sutton Parkway",
    "SNH":"St Helens Central",
    "BWK":"Berwick-Upon-Tweed",
    "NSB":"Normans Bay",
    "OXT":"Oxted",
    "KDB":"Kidbrooke",
    "UPT":"Upton (Merseyside)",
    "SON":"Steeton & Silsden",
    "CAD":"Cadoxton",
    "DWL":"Dawlish",
    "CBK":"Cranbrook",
    "LAR":"Largs",
    "WTG":"Watlington",
    "HID":"Hall-I'-Th'-Wood",
    "LCN":"Lincoln Central",
    "HNK":"Hinckley (Leics)",
    "LIS":"Liss",
    "TAB":"Tame Bridge Parkway",
    "ESD":"Elmstead Woods",
    "GIR":"Girvan",
    "DID":"Didcot Parkway",
    "LGJ":"Loughborough Junction",
    "ESL":"Eastleigh",
    "BBW":"Berry Brow",
    "BUK":"Bucknell",
    "KVD":"Kelvindale",
    "PWY":"Patchway",
    "RFY":"Rock Ferry",
    "FGT":"Faygate",
    "WCX":"Wembley Stadium",
    "WTC":"Whitchurch (Shropshire)",
    "DUL":"Dullingham",
    "FRI":"Frinton-On-Sea",
    "CAM":"Camberley",
    "LSN":"Livingston North",
    "WRP":"Warwick Parkway",
    "LOO":"Looe",
    "FZP":"Furze Platt",
    "HYH":"Hythe (Essex)",
    "THW":"The Hawthorns",
    "WSL":"Walsall",
    "UNI":"University (Birmingham)",
    "BIL":"Billingham (Cleveland)",
    "NUN":"Nuneaton",
    "BKD":"Blakedown",
    "RCA":"Risca & Pontymister",
    "BNG":"Bangor (Gwynedd)",
    "FGW":"Fishguard & Goodwick",
    "TOO":"Tooting",
    "CHW":"Chalkwell",
    "AMY":"Amberley",
    "RUN":"Runcorn",
    "FIN":"Finstock",
    "HCT":"Huncoat",
    "BTS":"Burntisland",
    "SDE":"Shadwell",
    "LLW":"Llwyngwril",
    "PMR":"Peckham Rye",
    "BNT":"Brinnington",
    "CTH":"Chadwell Heath",
    "SBS":"St Bees",
    "MDS":"Morden South",
    "BOG":"Bognor Regis",
    "MLB":"Millbrook (Beds)",
    "TUL":"Tulloch",
    "ACR":"Accrington",
    "TGM":"Teignmouth",
    "HRD":"Harling Road",
    "CHO":"Cholsey",
    "FML":"Frimley",
    "TAY":"Taynuilt",
    "PLU":"Plumstead",
    "BMF":"Broomfleet",
    "UHA":"Uphall",
    "UTY":"Upper Tyndrum",
    "WTL":"Whitland",
    "FKG":"Falkirk Grahamston",
    "SOT":"Stoke-On-Trent",
    "WMG":"Welham Green",
    "MIK":"Micklefield",
    "KGX":"Kings Cross",
    "CUM":"Culham",
    "FLF":"Flowery Field",
    "FNV":"Furness Vale",
    "COP":"Copplestone",
    "HGF":"Hag Fold",
    "MEO":"Meols",
    "DRM":"Drem",
    "LOC":"Lockerbie",
    "DEP":"Deptford",
    "BDN":"Brading",
    "CIL":"Chilham",
    "MFF":"Minffordd",
    "DLK":"Dalston Kingsland",
    "FNC":"Farncombe",
    "COI":"Crosshill",
    "THB":"Thornliebank",
    "BTP":"Braintree Freeport",
    "OTF":"Otford",
    "KMP":"Kempton Park Racecourse",
    "GER":"Gerrards Cross",
    "DVN":"Davenport",
    "RUS":"Ruswarp",
    "STL":"Southall",
    "CBN":"Camborne",
    "ZBK":"Barking Underground",
    "NOR":"Normanton",
    "KSN":"Kearsney (Kent)",
    "GLM":"Gillingham (Kent)",
    "GRB":"Great Bentley",
    "HKC":"Hackney Central",
    "GMN":"Great Missenden",
    "NMT":"Needham Market",
    "WFI":"Westerfield",
    "BCK":"Buckley",
    "EPS":"Epsom (Surrey)",
    "ACB":"Acton Bridge (Cheshire)",
    "WAM":"Walmer",
    "GCR":"Gloucester",
    "SMA":"Small Heath",
    "HRM":"Harrietsham",
    "ALX":"Alexandria",
    "CKS":"Clarkston",
    "BRA":"Brora",
    "TAU":"Taunton",
    "MRR":"Morar",
    "NWX":"New Cross",
    "DLM":"Delamere",
    "SPH":"Shepherds Well",
    "WSW":"Wandsworth Common",
    "MBR":"Middlesbrough",
    "SAW":"Sawbridgeworth",
    "CCT":"Cathcart",
    "SNK":"Sankey For Penketh",
    "WHG":"Westhoughton",
    "FNN":"Farnborough North",
    "DOR":"Dore & Totley",
    "BAG":"Bagshot",
    "SWO":"Snowdown",
    "TAI":"Tain",
    "ORE":"Ore",
    "HNW":"Hamilton West",
    "SLA":"Slateford",
    "BYB":"Blythe Bridge",
    "RDF":"Radcliffe-On-Trent",
    "NPD":"New Pudsey",
    "TDU":"Tondu",
    "ELE":"Elmers End",
    "ASB":"Ardrossan South Beach",
    "TRH":"Trehafod",
    "HCN":"Headcorn",
    "HYD":"Heyford",
    "BRW":"Brunswick",
    "FSG":"Fishersgate",
    "SBJ":"Stourbridge Junction",
    "CLW":"Chorleywood",
    "ATN":"Atherton (Manchester)",
    "DOT":"Dunston",
    "LIH":"Leigh (Kent)",
    "YRM":"Yarm",
    "INV":"Inverness",
    "BIG":"Billingshurst",
    "BCJ":"Burscough Junction",
    "FMR":"Falmer",
    "EAL":"Ealing Broadway",
    "CDT":"Caldicot",
    "CSY":"Coseley",
    "MIR":"Mirfield",
    "PLE":"Pollokshields East",
    "WHN":"Whiston",
    "CNG":"Congleton",
    "PBY":"Pembrey & Burry Port",
    "STW":"Strawberry Hill",
    "RHI":"Rhiwbina",
    "MDN":"Maiden Newton",
    "ANZ":"Anerley",
    "PMT":"Polmont",
    "AGT":"Aldrington",
    "SWY":"Sway",
    "PNY":"Pen-Y-Bont",
    "HNB":"Herne Bay",
    "SMN":"Southminster",
    "ROL":"Rolleston",
    "MLM":"Millom",
    "ZEL":"Elephant & Castle (Underground)",
    "SMT":"St Margarets (Herts)",
    "MAU":"Mauldeth Road",
    "SBF":"St Budeaux Ferry Road",
    "ALK":"Aslockton",
    "GFN":"Giffnock",
    "DMH":"Dilton Marsh",
    "YVJ":"Yeovil Junction",
    "GCW":"Glan Conwy",
    "CGM":"Cottingham",
    "NRD":"North Road (Darlington)",
    "MYH":"Maryhill",
    "LOT":"Lostock",
    "EBA":"Euxton Balshaw Lane",
    "BLK":"Blackrod",
    "HGR":"Hither Green",
    "RDB":"Redbridge",
    "CSW":"Chestfield & Swalecliffe",
    "CTN":"Charlton",
    "HKN":"Hucknall",
    "KVP":"Kiveton Park",
    "WSM":"Weston-Super-Mare",
    "EXC":"Exeter Central",
    "HTY":"Hattersley",
    "RHO":"Rhosneigr",
    "CAS":"Castleton (Manchester)",
    "LTG":"Lostock Gralam",
    "COT":"Cottingley",
    "TUR":"Turkey Street",
    "ELW":"Eltham",
    "HGM":"Higham (Kent)",
    "HMS":"Helmsdale",
    "NOA":"Newton-On-Ayr",
    "DFE":"Dunfermline Town",
    "DOW":"Downham Market",
    "SPA":"Spalding",
    "DDG":"Dorridge",
    "KCK":"Knockholt",
    "SID":"Sidcup",
    "BWB":"Bow Brickhill",
    "SOO":"Strood (Kent)",
    "PRR":"Princes Risborough",
    "NLT":"Northolt Park",
    "NWM":"New Milton",
    "HAT":"Hatfield (Herts)",
    "MBK":"Millbrook (Hants)",
    "LHE":"Loch Eil Outward Bound",
    "BCG":"Birchgrove",
    "ABY":"Ashburys",
    "BAN":"Banbury",
    "PST":"Prestonpans",
    "PEB":"Pevensey Bay",
    "CEL":"Chelford (Cheshire)",
    "INE":"Ince & Elton",
    "PUO":"Purley Oaks",
    "GIL":"Gillingham (Dorset)",
    "HLW":"Hillington West",
    "TLC":"Tal-Y-Cafn",
    "LGE":"Long Eaton",
    "NHD":"Nunhead",
    "FST":"Fenchurch Street",
    "RBR":"Robertsbridge",
    "MTA":"Mountain Ash",
    "SSD":"Stansted Airport",
    "RNR":"Roughton Road",
    "CMH":"Cwmbach",
    "HSB":"Helsby",
    "ALD":"Alderley Edge",
    "WGN":"Wigan North Western",
    "YRD":"Yardley Wood",
    "LHS":"Limehouse",
    "ROS":"Rosyth",
    "BYS":"Braystones (Cumbria)",
    "TGS":"Ty Glas",
    "SAA":"St Albans Abbey",
    "JHN":"Johnstone (Strathclyde)",
    "CSM":"Castleton Moor",
    "ECS":"Eccles Road",
    "CRG":"Cross Gates",
    "RML":"Romiley",
    "WAN":"Wanborough",
    "CUB":"Cumbernauld",
    "BES":"Bescar Lane",
    "SHT":"Shotton",
    "MLW":"Marlow",
    "ANF":"Ashurst New Forest",
    "HTN":"Hatton",
    "GRS":"Garscadden",
    "BNP":"Barnstaple",
    "ACY":"Abercynon",
    "SJS":"St James Street (Walthamstow)",
    "MAR":"Margate",
    "BIY":"Bingley",
    "SNO":"St Neots",
    "KGL":"Kings Langley",
    "KTW":"Kentish Town West",
    "AUW":"Ascott-Under-Wychwood",
    "CPH":"Caerphilly",
    "SCR":"St Columb Road",
    "PEV":"Pevensey & Westham",
    "BAI":"Blairhill",
    "CIR":"Caledonian Rd & Barnsbury",
    "GBK":"Greenbank",
    "CRS":"Carstairs",
    "CKT":"Crookston",
    "MAI":"Maidenhead",
    "SAC":"St Albans",
    "WNP":"Wanstead Park",
    "LES":"Leigh-On-Sea",
    "PHG":"Penhelig",
    "STU":"Sturry",
    "OUT":"Outwood",
    "DAR":"Darlington",
    "HMY":"Hairmyres",
    "ZBB":"Barbican",
    "EUS":"London Euston",
    "HNT":"Huntly",
    "PRH":"Penrhyndeudraeth",
    "RYP":"Ryde Pier Head",
    "ROW":"Rowley Regis",
    "NMN":"New Mills Newtown",
    "ESM":"Elsenham (Essex)",
    "NEW":"Newcraighall",
    "UDD":"Uddingston",
    "BXB":"Broxbourne",
    "SHS":"Shotts",
    "HOP":"Hope (Derbyshire)",
    "PTR":"Petersfield",
    "KGX":"London Kings Cross",
    "SVR":"Silverdale",
    "DLS":"Dalston (Cumbria)",
    "EWD":"Earlswood (West Midlands)",
    "CYS":"Cathays",
    "CFN":"Clifton Down",
    "ABC":"Altnabreac",
    "HHL":"Heath High Level",
    "BIN":"Bingham",
    "MOT":"Motspur Park",
    "RHM":"Reedham (Surrey)",
    "AST":"Aston",
    "SPI":"Spital",
    "DLY":"Dalry",
    "NCM":"North Camp",
    "WHP":"West Hampstead Thameslink",
    "HMT":"Ham Street",
    "ASS":"Alness",
    "RYN":"Roydon",
    "SOE":"Southend East",
    "BUW":"Burley-In-Wharfedale",
    "LGF":"Longfield",
    "OXF":"Oxford",
    "PES":"Pensarn (Gwynedd)",
    "EBV":"Ebbw Vale Parkway",
    "GOM":"Gomshall",
    "WHS":"Whyteleafe South",
    "ROO":"Roose",
    "WIC":"Wickford",
    "HAZ":"Hazel Grove",
    "RHL":"Rhyl",
    "PYJ":"Paisley St James",
    "CAU":"Causeland",
    "WPE":"Wapping",
    "MLY":"Morley",
    "POR":"Porth",
    "BUH":"Brough",
    "HRY":"Harringay Green Lanes",
    "NCE":"New Clee",
    "SEH":"Shoreham (Kent)",
    "RUA":"Ruabon",
    "PMW":"Penmaenmawr",
    "SPP":"Shippea Hill",
    "ELO":"Elton & Orston",
    "PTB":"Pentre-Bach",
    "RAD":"Radley",
    "HAY":"Hayes & Harlington",
    "WNE":"Wilnecote (Staffs)",
    "SMK":"Stowmarket",
    "CHT":"Chathill",
    "OHL":"Old Hill",
    "SRD":"Stapleton Road",
    "CBS":"Coatbridge Sunnyside",
    "TOK":"Three Oaks",
    "ROM":"Romsey",
    "THC":"Thurnscoe",
    "KKN":"Kirknewton",
    "HUP":"Humphrey Park",
    "WRK":"Worksop",
    "WPL":"Worplesdon",
    "WDB":"Woodbridge",
    "TIS":"Tisbury",
    "FRY":"Ferriby",
    "EXD":"Exeter St David'S",
    "CWD":"Creswell",
    "PRU":"Prudhoe",
    "SAT":"South Acton",
    "MPL":"Marple",
    "GNR":"Green Road",
    "EKL":"East Kilbride",
    "FGH":"Fishguard Harbour",
    "NWN":"Newton For Hyde",
    "GRK":"Gourock",
    "DBE":"Dumbarton East",
    "ARL":"Arlesey",
    "WMR":"Widney Manor",
    "GTO":"Gorton",
    "IFI":"Ifield",
    "BRR":"Barrhead",
    "GRC":"Great Chesterford",
    "SUO":"Sutton (Surrey)",
    "HRS":"Horsforth",
    "UPW":"Upwey",
    "SUY":"Sudbury (Suffolk)",
    "DEN":"Dean (Wilts)",
    "KRK":"Kirkconnel",
    "LHA":"Loch Awe",
    "MSH":"Mossley Hill",
    "ULC":"Ulceby",
    "LTP":"Littleport",
    "CDI":"Crediton",
    "SER":"St Erth",
    "UMB":"Umberleigh",
    "HOZ":"Howwood (Renfrewshire)",
    "PYP":"Pont-Y-Pant",
    "AVN":"Avonmouth",
    "THE":"Theale",
    "LBO":"Loughborough",
    "OUN":"Oulton Broad North",
    "BHD":"Brithdir",
    "NRW":"Norwich",
    "AGL":"Abergele & Pensarn",
    "CODE":"Station Name",
    "BMV":"Bromsgrove",
    "PNF":"Penyffordd",
    "ACG":"Acocks Green",
    "HCB":"Hackbridge",
    "EFF":"Effingham Junction",
    "HWN":"Harlow Town",
    "WCF":"Westcliff",
    "CNL":"Canley",
    "FKC":"Folkestone Central",
    "SCF":"Stechford",
    "LTT":"Little Sutton",
    "MNN":"Menston",
    "SOK":"South Kenton",
    "ASH":"Ash",
    "LID":"Lidlington",
    "RIA":"Rhoose Cardiff International Airport",
    "HML":"Hemel Hempstead",
    "HLD":"Hellifield",
    "NBT":"Norbiton",
    "HUT":"Hutton Cranswick",
    "STK":"Stockton",
    "LLJ":"Llandudno Junction",
    "WSA":"West Allerton",
    "BLY":"Bletchley",
    "FAL":"Falmouth Docks",
    "BSH":"Bushey",
    "SAU":"St Austell",
    "NEM":"New Malden",
    "WLD":"West St Leonards",
    "HEN":"Hendon",
    "MDE":"Maidstone East",
    "HGT":"Harrogate",
    "BMT":"Bedminster",
    "UHL":"Upper Holloway",
    "GPO":"Gospel Oak",
    "AVY":"Aberdovey",
    "EBK":"Eastbrook",
    "LGN":"Longton",
    "MTV":"Mount Vernon",
    "PPD":"Pontypridd",
    "DMF":"Dumfries",
    "FRO":"Frome",
    "BRN":"Bearsden",
    "DGT":"Deansgate",
    "LYT":"Lymington Town",
    "PYC":"Pontyclun",
    "CHU":"Cheadle Hulme",
    "MRB":"Manorbier",
    "WIH":"Winchmore Hill",
    "BDQ":"Bradford Forster Square",
    "HOK":"Hook",
    "LLY":"Llwynypia",
    "SKG":"Skegness",
    "LLH":"Llangennech",
    "LTL":"Littleborough",
    "HWB":"Hawarden Bridge",
    "SCG":"Stone Crossing",
    "CHX":"Charing Cross",
    "STC":"Strathcarron",
    "SUC":"Sutton Common",
    "CHH":"Christ'S Hospital",
    "BGN":"Bridgend",
    "BNI":"Barnes Bridge",
    "HUR":"Hurst Green",
    "ARG":"Arisaig",
    "AXP":"Alexandra Parade",
    "MEP":"Meopham",
    "LHO":"Langho",
    "KWL":"Kidwelly",
    "WFJ":"Watford Junction",
    "DGL":"Dingle Road",
    "LVN":"Littlehaven",
    "BLO":"Blaydon",
    "RDD":"Riddlesdown",
    "SOB":"Southbourne",
    "STT":"Stewarton",
    "NNP":"Ninian Park",
    "ART":"Arrochar & Tarbet",
    "RGL":"Rugeley Trent Valley",
    "WNF":"Winchfield",
    "EGH":"Egham",
    "CBB":"Carbis Bay",
    "CBL":"Cambuslang",
    "KNT":"Kenton",
    "RMB":"Roman Bridge",
    "LLC":"Llandecwyn",
    "SYH":"Sydenham Hill",
    "AHS":"Ashurst (Kent)",
    "NFL":"Northfleet",
    "GRT":"Grateley",
    "GRH":"Gartcosh",
    "ABA":"Aberdare",
    "LST":"London Liverpool Street",
    "BAM":"Bamford",
    "LGB":"Langbank",
    "PNZ":"Penzance",
    "PGN":"Paignton",
    "DND":"Dinsdale",
    "HOL":"Holton Heath",
    "COY":"Coryton",
    "WRM":"Wareham (Dorset)",
    "CGD":"Craigendoran",
    "RYD":"Ryde Esplanade",
    "TAC":"Tackley",
    "CSL":"Codsall",
    "NWA":"North Walsham",
    "KPT":"Kilpatrick",
    "CEF":"Chapel-En-Le-Frith",
    "BIS":"Bishops Stortford",
    "CRV":"Craven Arms",
    "CAN":"Carnoustie",
    "CBD":"Conon Bridge",
    "NBW":"North Berwick",
    "BKR":"Blackridge",
    "BWT":"Bridgwater",
    "BKA":"Bookham",
    "KKD":"Kirkdale",
    "SIC":"Silecroft",
    "LAC":"Lancing",
    "EMS":"Emsworth",
    "PEG":"Pegswood",
    "ADL":"Adlington (Lancs)",
    "BSN":"Boston",
    "HUN":"Huntingdon",
    "LLM":"Llangammarch",
    "HMC":"Hampton Court",
    "WKF":"Wakefield Westgate",
    "NVH":"Newhaven Harbour",
    "TOM":"Tottenham Hale",
    "BHK":"Bush Hill Park",
    "HEW":"Heworth",
    "RSH":"Rose Hill Marple",
    "PSL":"Port Sunlight",
    "WHC":"Walthamstow Central",
    "WAR":"Ware (Herts)",
    "HOT":"Henley-On-Thames",
    "DYP":"Drayton Park",
    "NWI":"Northwich",
    "FNH":"Farnham",
    "SPS":"Stepps",
    "RTR":"Rochester",
    "UPL":"Upholland",
    "OVE":"Overpool",
    "SDC":"Shoreditch High Street",
    "EBR":"Edenbridge (Kent)",
    "SLY":"Selly Oak",
    "BEU":"Beaulieu Road",
    "BND":"Brandon",
    "MES":"Melton (Suffolk)",
    "JOH":"Johnston (Pembs)",
    "MCB":"Moulsecoomb",
    "DMC":"Drumchapel",
    "WYE":"Wye",
    "WFL":"Wainfleet",
    "ADK":"Ardwick",
    "BTT":"Battersby",
    "RUE":"Runcorn East",
    "NBN":"New Brighton",
    "KEN":"Kendal",
    "ELR":"Elsecar",
    "DNL":"Dunlop",
    "WEY":"Weymouth",
    "BOR":"Bodorgan",
    "ZCW":"Canada Water",
    "BUS":"Busby",
    "CPT":"Clapton",
    "EBD":"Ebbsfleet International",
    "CUF":"Cuffley",
    "VIC":"Victoria",
    "HTO":"Hightown",
    "SYA":"Styal",
    "SLB":"Saltburn",
    "LLD":"Llandudno",
    "ADN":"Ardrossan Town",
    "DRN":"Duirinish",
    "FLI":"Flixton",
    "WEL":"Wellingborough",
    "SPU":"Staplehurst",
    "CSH":"Carshalton",
    "WNT":"Wandsworth Town",
    "PRL":"Prittlewell",
    "CRY":"Crayford",
    "WRY":"Wraysbury",
    "DBL":"Dunblane",
    "AHN":"Ashton-Under-Lyne",
    "WWL":"Whitwell (Derbyshire)",
    "HMD":"Hampden Park (Sussex)",
    "SLW":"Salwick",
    "ECL":"Eccleston Park",
    "CFL":"Crossflatts",
    "KGH":"Kinghorn",
    "BSS":"Barassie",
    "CTR":"Chester",
    "MNP":"Manor Park",
    "KSL":"Kearsley (Manchester)",
    "BIP":"Bishopstone (Sussex)",
    "EDY":"East Didsbury",
    "CMD":"Camden Road",
    "WIL":"Willington",
    "GLC":"Glasgow Central",
    "APG":"Aspley Guise",
    "BUB":"Burnley Barracks",
    "BBS":"Bordesley",
    "RLG":"Rayleigh",
    "GLZ":"Glazebrook",
    "EGR":"East Grinstead",
    "LIC":"Lichfield City",
    "HBD":"Hebden Bridge",
    "BWN":"Bloxwich North",
    "CBW":"Canterbury West",
    "HIL":"Hillside",
    "BKP":"Birkenhead Park",
    "SHR":"Shrewsbury",
    "BYI":"Barry Island",
    "MSO":"Moston",
    "MNR":"Manor Road",
    "HSK":"Hassocks",
    "THL":"Tile Hill",
    "CRA":"Cradley Heath",
    "SOF":"South Woodham Ferrers",
    "SYS":"Syston",
    "PNE":"Penge East",
    "WSB":"Westbury (Wilts)",
    "SRO":"Shireoaks",
    "SWT":"Slaithwaite",
    "BUO":"Bursledon",
    "ATH":"Atherstone",
    "QPK":"Queens Park (Glasgow)",
    "KBX":"Kirby Cross",
    "CSG":"Cressington",
    "WWA":"Woolwich Arsenal",
    "QPW":"Queens Park (London)",
    "SDH":"Sudbury Hill Harrow",
    "MRF":"Moorfields",
    "EFL":"East Farleigh",
    "SDL":"Sandhills",
    "BEE":"Beeston",
    "HKM":"Hykeham",
    "FIT":"Filton Abbey Wood",
    "AUI":"Ardlui",
    "LLN":"Llandaf",
    "NWE":"Newport (Essex)",
    "RGW":"Ramsgreave & Wilpshire",
    "REI":"Reigate",
    "WMW":"Walthamstow Queen'S Road",
    "MDL":"Middlewood",
    "BYM":"Burnley Manchester Road",
    "CUH":"Curriehill",
    "GRV":"Gravesend",
    "PNR":"Penrith (North Lakes)",
    "KMH":"Kempston Hardwick",
    "PTL":"Priesthill & Darnley",
    "DFL":"Dunfermline Queen Margaret",
    "LUT":"Luton",
    "WNY":"White Notley",
    "LAD":"Ladywell",
    "ZWL":"Whitechapel",
    "TRN":"Troon",
    "STG":"Stirling",
    "BOP":"Bowes Park",
    "SDW":"Sandwich",
    "BNC":"Burnley Central",
    "DYC":"Dyce",
    "SML":"Sea Mills",
    "GGV":"Gargrave",
    "TYW":"Tywyn",
    "CRL":"Chorley",
    "DVP":"Dover Priory",
    "BGI":"Bargeddie",
    "MUI":"Muirend",
    "WNM":"Weston Milton",
    "GCT":"Great Coates",
    "BSP":"Brondesbury Park",
    "DMY":"Drumry",
    "BLA":"Blair Atholl",
    "MEW":"Maesteg (Ewenny Road)",
    "HHE":"Haywards Heath",
    "SFD":"Salford Central",
    "INT":"Ingatestone",
    "BSV":"Buckshaw Parkway",
    "MIC":"Micheldever",
    "WLF":"Whittlesford Parkway",
    "HED":"Halewood",
    "ABD":"Aberdeen",
    "HAF":"Heathrow Airport Terminal 4",
    "HWV":"Heathrow Airport Terminal 5",
    "LAN":"Lancaster",
    "ACC":"Acton Central",
    "CEA":"Cleland",
    "BMO":"Birmingham Moor Street",
    "HEV":"Hever",
    "BLX":"Bloxwich",
    "NES":"Neston",
    "HAG":"Hagley",
    "RYR":"Ryde St Johns Road",
    "BTE":"Bitterne",
    "DIG":"Digby & Sowton",
    "EXG":"Exhibition Centre (Glasgow)",
    "ALW":"Allens West",
    "SAH":"Salhouse",
    "ALT":"Altrincham",
    "RVN":"Ravensthorpe",
    "WLO":"Waterloo (Merseyside)",
    "BEF":"Benfleet",
    "SOG":"Stonegate",
    "PWW":"Pollokshaws West",
    "SUR":"Surbiton",
    "EXM":"Exmouth",
    "TYG":"Tygwyn",
    "SVG":"Stevenage",
    "HIT":"Hitchin",
    "LPY":"Liverpool South Parkway",
    "SUD":"Sudbury & Harrow Road",
    "SKM":"Stoke Mandeville",
    "SEA":"Seaham",
    "LEE":"Lee (London)",
    "HNA":"Hinton Admiral",
    "MSN":"Marsden (Yorks)",
    "RDT":"Radlett",
    "PTC":"Portchester",
    "LBR":"Llanbedr",
    "SPT":"Stockport",
    "MAG":"Maghull",
    "DBC":"Dumbarton Central",
    "FMT":"Falmouth Town",
    "YRT":"Yorton",
    "SFL":"Seaforth & Litherland",
    "DLJ":"Dalston Junction",
    "HPA":"Honor Oak Park",
    "PFM":"Pontefract Monkhill",
    "FZH":"Frizinghall",
    "PYG":"Paisley Gilmour Street",
    "ATT":"Attadale",
    "LDS":"Leeds",
    "YAT":"Yatton",
    "ASI":"Ashford International (Eurostar)",
    "EDP":"Edinburgh Park",
    "HLI":"Healing",
    "BRH":"Borth",
    "SNW":"Swanwick",
    "BDG":"Bridgeton",
    "MIA":"Manchester Airport",
    "LZB":"Lazonby & Kirkoswald",
    "GNT":"Gunton",
    "WHR":"West Horndon",
    "HFN":"Hertford North",
    "LLV":"Llandovery",
    "PRT":"Prestatyn",
    "PLT":"Pontlottyn",
    "MST":"Maesteg",
    "SPX":"London St Pancras (Intl)",
    "GLO":"Glossop",
    "TRY":"Treorchy",
    "SCU":"Scunthorpe",
    "CHM":"Chelmsford",
    "LMS":"Leamington Spa",
    "MCN":"Machynlleth",
    "CFO":"Chalfont & Latimer",
    "APS":"Apsley",
    "FRL":"Fairlie",
    "HHD":"Holyhead",
    "QUI":"Quintrell Downs",
    "CAC":"Caldercruix",
    "EYN":"Eynsford",
    "KBN":"Kilburn High Road",
    "THH":"Thatto Heath",
    "TEY":"Teynham",
    "BTF":"Bottesford",
    "SSC":"Seascale",
    "MSL":"Mossley (Manchester)",
    "MKC":"Milton Keynes Central",
    "CST":"London Cannon Street",
    "ECC":"Eccles (Manchester)",
    "RHY":"Rhymney",
    "NBY":"Newbury",
    "WEH":"West Ham",
    "WFN":"Watford North",
    "BAJ":"Baglan",
    "WLT":"Wallington",
    "PUT":"Putney",
    "PPL":"Pontypool & New Inn",
    "APD":"Appledore (Kent)",
    "WDD":"Widdrington",
    "CME":"Combe (Oxon)",
    "SVL":"Staveley (Cumbria)",
    "BUD":"Burneside (Cumbria)",
    "SUM":"Summerston",
    "KNN":"Kings Norton",
    "SNE":"Stone (Staffs)",
    "ANS":"Ainsdale",
    "DPS":"Dublin Port - Stena",
    "TTH":"Thornton Heath",
    "GUN":"Gunnersbury",
    "FOX":"Foxfield",
    "WMA":"West Malling",
    "HAC":"Hackney Downs",
    "ZHS":"High Street Kensington Underground",
    "WGV":"Wargrave",
    "LIN":"Linlithgow",
    "SLR":"Sleaford",
    "FSB":"Fishbourne (Sussex)",
    "PEM":"Pemberton",
    "COV":"Coventry",
    "HAL":"Hale (Manchester)",
    "NCL":"Newcastle",
    "LPR":"Long Preston",
    "LEL":"Lelant",
    "BLE":"Bramley (W Yorks)",
    "PIT":"Pitlochry",
    "AMR":"Amersham",
    "ROB":"Roby",
    "CNY":"Cantley",
    "TRM":"Trimley",
    "BSR":"Broadstairs",
    "KGP":"Kings Park",
    "MNE":"Manea",
    "LED":"Ledbury",
    "FLE":"Fleet",
    "HAM":"Hamworthy",
    "SYD":"Sydenham (London)",
    "CSD":"Cobham & Stoke D'Abernon",
    "PTT":"Patterton",
    "WOM":"Wombwell",
    "APB":"Appley Bridge",
    "CLG":"Claygate",
    "TBW":"Tunbridge Wells",
    "WNC":"Windsor & Eton Central",
    "NSH":"North Sheen",
    "THT":"Thorntonhall",
    "FST":"London Fenchurch Street",
    "STS":"Saltash",
    "BLM":"Belmont",
    "EDG":"Edge Hill",
    "HDW":"Hadley Wood",
    "GOS":"Grange-Over-Sands",
    "BCN":"Branchton",
    "WHL":"White Hart Lane",
    "SHC":"Streethouse",
    "MEC":"Meols Cop",
    "SHY":"Shipley (Yorks)",
    "IRV":"Irvine",
    "CWB":"Colwyn Bay",
    "HSG":"Hathersage",
    "AIN":"Aintree",
    "CNF":"Carnforth",
    "DRU":"Drumgelloch",
    "WWR":"Wandsworth Road",
    "WLP":"Welshpool",
    "SWL":"Swale",
    "BNS":"Barnes",
    "GOE":"Goldthorpe",
    "GRF":"Garforth",
    "KTH":"Kent House",
    "BFE":"Bere Ferrers",
    "DKT":"Dorking West",
    "HNG":"Hengoed",
    "WBC":"Waterbeach",
    "RSG":"Rose Grove",
    "OPK":"Orrell Park",
    "ECR":"East Croydon",
    "KBF":"Kirkby-In-Furness",
    "WRB":"Wrabness",
    "LVJ":"Liverpool James Street",
    "RDR":"Radyr",
    "UCK":"Uckfield",
    "ABH":"Abererch",
    "EWE":"Ewell East",
    "GLQ":"Glasgow Queen Street",
    "MAL":"Malden Manor",
    "BDK":"Baldock",
    "MPT":"Morpeth",
    "HRL":"Harlech",
    "SHL":"Shawlands",
    "SKS":"Stocksfield",
    "RAM":"Ramsgate",
    "DBY":"Derby",
    "SEM":"Seamer",
    "GST":"Gathurst",
    "MHM":"Merstham",
    "LEG":"Lea Green",
    "LVT":"Lisvane & Thornhill",
    "LNZ":"Lenzie",
    "STH":"Shepreth",
    "LGD":"Lingwood",
    "BRG":"Borough Green & Wrotham",
    "CDR":"Cardross",
    "SOP":"Southport",
    "NTN":"Newton (Lanark)",
    "HMM":"Hammerton",
    "PLM":"Plumley",
    "IRL":"Irlam",
    "POL":"Polsloe Bridge",
    "WCH":"Whitchurch (Hants)",
    "BTL":"Batley",
    "WCB":"Westcombe Park",
    "HWC":"Harwich Town",
    "WET":"Weeton",
    "KYN":"Keynsham",
    "PMA":"Portsmouth Arms",
    "MOO":"Muir Of Ord",
    "HLY":"Holytown",
    "HTF":"Hartford (Cheshire)",
    "KBK":"Kents Bank",
    "HGS":"Hastings",
    "AMF":"Ammanford",
    "IBM":"Ibm Halt",
    "WRT":"Worstead",
    "SIP":"Shipton",
    "LOF":"London Fields",
    "CFR":"Chandlers Ford",
    "LLT":"Llanbister Road",
    "ENL":"Enfield Lock",
    "FRM":"Fareham",
    "MGN":"Marston Green",
    "CUP":"Cupar",
    "HLM":"Holmwood",
    "BBK":"Bilbrook",
    "GCH":"Garelochhead",
    "FEA":"Featherstone",
    "LDN":"Llandanwg",
    "SDG":"Sandling",
    "SQE":"Surrey Quays",
    "NLW":"Newton-Le-Willows",
    "WIJ":"Willesden Junction",
    "EXN":"Exton",
    "DTN":"Denton",
    "SPO":"Spondon",
    "GNW":"Greenwich",
    "BWO":"Bricket Wood",
    "BPW":"Bristol Parkway",
    "WKG":"Workington",
    "SWN":"Swinton (South Yorks)",
    "MLD":"Mouldsworth",
    "CBP":"Castle Bar Park",
    "ELY":"Ely",
    "BRO":"Bridge Of Orchy",
    "PLC":"Pluckley",
    "JOR":"Jordanhill",
    "OLD":"Old Street",
    "CPA":"Corpach",
    "TRF":"Trefforest",
    "CGW":"Caergwrle",
    "FAV":"Faversham",
    "NBA":"New Barnet",
    "RVB":"Ravensbourne",
    "WTS":"Whatstandwell",
    "MCH":"March",
    "ASN":"Addlestone",
    "MLT":"Malton",
    "TED":"Teddington",
    "RDM":"Riding Mill",
    "TUT":"Tutbury & Hatton",
    "LLA":"Llanaber",
    "WTO":"Water Orton",
    "SBM":"South Bermondsey",
    "FOR":"Forres",
    "ACK":"Acklington",
    "OLT":"Olton",
    "ARM":"Armadale (West Lothian)",
    "SOR":"Sole Street",
    "WMI":"Wildmill",
    "TTN":"Totton",
    "PLN":"Portlethen",
    "MPK":"Mosspark",
    "CLE":"Cleethorpes",
    "BUG":"Burgess Hill",
    "BMR":"Bromborough Rake",
    "BHR":"Builth Road",
    "CSA":"Cosham",
    "CRB":"Corbridge",
    "WOF":"Worcester Foregate Street",
    "STO":"South Tottenham",
    "GUI":"Guide Bridge",
    "NWB":"North Wembley",
    "FRD":"Frodsham",
    "SBK":"South Bank",
    "SPB":"Shepherd'S Bush",
    "WDN":"Walsden",
    "CAY":"Carntyne",
    "BSB":"Bleasby",
    "WVH":"Wolverhampton",
    "RYS":"Royston",
    "GTH":"Garth (Powys)",
    "DLR":"Dalreoch",
    "DEA":"Deal",
    "MIJ":"Mitcham Junction",
    "AXM":"Axminster",
    "BTH":"Bath Spa",
    "BIT":"Bicester Town",
    "CTE":"Chatelherault",
    "THA":"Thatcham",
    "CRR":"Corrour",
    "LLO":"Llandrindod",
    "INH":"Invershin",
    "TPB":"Thorpe Bay",
    "CUX":"Cuxton",
    "GDH":"Gordon Hill",
    "WDO":"Waddon",
    "WML":"Wilmslow",
    "BNL":"Barnhill",
    "HMN":"Homerton",
    "BNE":"Bourne End",
    "KEI":"Keighley",
    "NWD":"Norwood Junction",
    "HHB":"Heysham Port",
    "WAO":"Walton (Merseyside)",
    "LLL":"Llandeilo",
    "MYB":"London Marylebone",
    "TRO":"Trowbridge",
    "PAT":"Patricroft",
    "CIT":"Chislehurst",
    "WID":"Widnes",
    "GLE":"Gleneagles",
    "CRN":"Crowthorne",
    "STM":"St Michaels",
    "WCM":"Wickham Market",
    "KNI":"Knighton",
    "IFD":"Ilford",
    "AMT":"Aldermaston",
    "HLN":"Harlington (Beds)",
    "ANN":"Annan",
    "LOW":"Lowdham",
    "DCH":"Dorchester South",
    "RID":"Ridgmont",
    "HEI":"Heighington",
    "DAK":"Dalmarnock",
    "NSG":"New Southgate",
    "LLE":"Llanelli",
    "PNC":"Penychain",
    "SMC":"Sampford Courtenay",
    "HPT":"Hopton Heath",
    "NMK":"Newmarket",
    "MAC":"Macclesfield",
    "RGT":"Rugeley Town",
    "CRD":"Chester Road",
    "HYC":"Hyde Central",
    "BWS":"Barrow-Upon-Soar",
    "SCS":"Starcross",
    "AYP":"Albany Park",
    "WYL":"Wylde Green",
    "GBS":"Goring-By-Sea",
    "LEO":"Leominster",
    "BBN":"Blackburn",
    "TOP":"Topsham",
    "BPN":"Blackpool North",
    "ARD":"Ardgay",
    "DYF":"Dyffryn Ardudwy",
    "WTY":"Witley",
    "SJP":"St James Park (Exeter)",
    "SOL":"Solihull",
    "INC":"Ince (Manchester)",
    "ULL":"Ulleskelf",
    "PFR":"Pontefract Baghill",
    "SFO":"Stanford-Le-Hope",
    "VIR":"Virginia Water",
    "HAI":"Halling",
    "HNH":"Herne Hill",
    "LRH":"Larkhall",
    "DLT":"Dalton (Cumbria)",
    "NLR":"North Llanrwst",
    "HTW":"Hartwood",
    "TBY":"Thornaby",
    "ABE":"Aber",
    "BDT":"Bridlington",
    "NUM":"Northumberland Park",
    "FER":"Fernhill",
    "SWE":"Swineshead",
    "WRW":"Warwick",
    "MTP":"Montpelier",
    "CLP":"Clapham High Street",
    "ALB":"Albrighton",
    "WLC":"Waltham Cross",
    "SAL":"Salisbury",
    "PRN":"Parton",
    "RMC":"Rotherham Central",
    "RNF":"Rainford",
    "HOX":"Hoxton",
    "WLV":"Wallasey Village",
    "CSB":"Carshalton Beeches",
    "ANG":"Angmering",
    "NBC":"New Beckenham",
    "WOK":"Woking",
    "CRE":"Crewe",
    "KTN":"Kentish Town",
    "NSD":"Newstead",
    "HLR":"Hall Road",
    "WDS":"Woodlesford",
    "LKE":"Lake",
    "SUT":"Sutton Coldfield",
    "EAD":"Earlsfield",
    "SAR":"St Andrews Road",
    "CNW":"Conwy",
    "ADC":"Adlington (Cheshire)",
    "CHY":"Chertsey",
    "LGO":"Llangynllo",
    "CET":"Colchester Town",
    "AYH":"Aylesham",
    "BDY":"Bredbury",
    "MRN":"Marden (Kent)",
    "MFA":"Morfa Mawddach",
    "LCG":"Lochgelly",
    "DEW":"Dewsbury",
    "NFA":"North Fambridge",
    "FIL":"Filey",
    "SIN":"Singer",
    "FAZ":"Fazakerley",
    "FOD":"Ford",
    "BDW":"Bedwyn",
    "WBY":"West Byfleet",
    "BTO":"Betchworth",
    "HBN":"Hollingbourne",
    "AGR":"Angel Road",
    "WRL":"Wetheral",
    "LEN":"Lenham",
    "SLK":"Silkstone Common",
    "NAR":"Narberth",
    "LWM":"Llantwit Major",
    "BHS":"Brockholes",
    "BMS":"Bromley South",
    "PMH":"Portsmouth Harbour",
    "FPK":"Finsbury Park",
    "LGM":"Langley Mill",
    "PON":"Ponders End",
    "BOE":"Botley",
    "DPD":"Dorking Deepdene",
    "HOU":"Hounslow",
    "TNF":"Tonfanau",
    "EXR":"Essex Road",
    "PLY":"Plymouth",
    "LOB":"Longbridge",
    "DRG":"Drayton Green",
    "AYR":"Ayr",
    "BRI":"Bristol Temple Meads",
    "ROR":"Rogerstone",
    "PTM":"Porthmadog",
    "ING":"Invergowrie",
    "AHT":"Aldershot",
    "MIL":"Mill Hill Broadway",
    "CES":"Cressing (Essex)",
    "AGS":"Argyle Street",
    "DBG":"Mottisfont & Dunbridge",
    "CSS":"Chessington South",
    "CYB":"Cefn-Y-Bedd",
    "AUR":"Aberdour",
    "TWI":"Twickenham",
    "GPK":"Grange Park",
    "KGN":"Kings Nympton",
    "MNC":"Markinch",
    "SWG":"Swaythling",
    "CWM":"Cwmbran",
    "LYD":"Lydney",
    "TWN":"Town Green",
    "FYS":"Ferryside",
    "SGB":"Smethwick Galton Bridge",
    "BSL":"Beasdale",
    "SGR":"Slade Green",
    "BXD":"Buxted",
    "NCT":"Newark Castle",
    "WAV":"Wavertree Technology Park",
    "BKM":"Berkhamsted",
    "FNR":"Farningham Road",
    "HYW":"Hinchley Wood",
    "CST":"Cannon Street",
    "SRG":"Seer Green & Jordans",
    "SAY":"Swanley",
    "MOS":"Moss Side",
    "OBN":"Oban",
    "FRN":"Fearn",
    "HBP":"Hornbeam Park",
    "BBL":"Bat & Ball",
    "ADS":"Ardrossan Harbour",
    "MDB":"Maidstone Barracks",
    "DSL":"Disley",
    "HBY":"Hartlebury",
    "WEA":"West Ealing",
    "SSM":"Stocksmoor",
    "CWC":"Chappel & Wakes Colne",
    "CLD":"Chelsfield",
    "PTW":"Prestwick Town",
    "LNB":"Llanbradach",
    "CYT":"Cherry Tree",
    "BMP":"Brampton (Cumbria)",
    "BYL":"Barry Links",
    "SWM":"Swanscombe",
    "HST":"High Street (Glasgow)",
    "LIP":"Liphook",
    "CRK":"Chirk",
    "AUK":"Auchinleck",
    "DFR":"Drumfrochar",
    "WKM":"Wokingham",
    "MTB":"Matlock Bath",
    "MYT":"Mytholmroyd",
    "QRB":"Queenstown Road (Battersea)",
    "PLK":"Plockton",
    "INR":"Inverurie",
    "PNS":"Penistone",
    "AVF":"Avoncliff",
    "HAS":"Halesworth",
    "HYT":"Hyde North",
    "DAN":"Darnall",
    "LVC":"Liverpool Central",
    "WSH":"Wishaw",
    "SHE":"Sherborne",
    "UPM":"Upminster",
    "HDH":"Hampstead Heath",
    "SLL":"Stallingborough",
    "WBQ":"Warrington Bank Quay",
    "SHF":"Sheffield",
    "BLB":"Battlesbridge",
    "CRH":"Crouch Hill",
    "GSY":"Guiseley",
    "WAC":"Warrington Central",
    "CRI":"Cricklewood",
    "AIG":"Aigburth",
    "OXN":"Oxenholme Lake District",
    "OVR":"Overton",
    "MAT":"Matlock",
    "MFT":"Mansfield",
    "DFI":"Duffield",
    "HUL":"Hull",
    "NLS":"Nailsea & Backwell",
    "WLY":"Woodley",
    "CNP":"Conway Park",
    "CTK":"City Thameslink",
    "SGL":"South Gyle",
    "YOK":"Yoker",
    "HPN":"Hapton",
    "DAG":"Dalgety Bay",
    "SOC":"Southend Central",
    "TNP":"Tonypandy",
    "SBR":"Spean Bridge",
    "REE":"Reedham (Norfolk)",
    "CWL":"Colwall",
    "BGM":"Bellingham",
    "MIN":"Milliken Park",
    "MOG":"Moorgate",
    "ISL":"Isleworth",
    "BAT":"Battle",
    "GRY":"Grays",
    "SSE":"Shoreham-By-Sea",
    "TRD":"Troed-Y-Rhiw",
    "WXC":"Wrexham Central",
    "KNU":"Knucklas",
    "DCW":"Dorchester West",
    "SES":"South Elmsall",
    "WGA":"Westgate-On-Sea",
    "DLH":"Doleham",
    "BEG":"Beltring",
    "DNM":"Denham",
    "CWU":"Crowhurst",
    "FZW":"Fitzwilliam",
    "TAL":"Talsarnau",
    "SRH":"Streatham Hill",
    "BME":"Broome",
    "COH":"Crowborough",
    "FTM":"Fort Matilda",
    "MYL":"Maryland",
    "HPQ":"Harwich International",
    "WBO":"Wimbledon Chase",
    "ASG":"Alsager",
    "BSM":"Branksome",
    "BTN":"Brighton (East Sussex)",
    "CUA":"Culrain",
    "BDM":"Bedford",
    "SBP":"Stonebridge Park",
    "FRS":"Forsinard",
    "WLI":"Welling",
    "KML":"Kemsley",
    "HOC":"Hockley",
    "HNX":"Hunts Cross",
    "LEY":"Leyland",
    "HOV":"Hove",
    "MZH":"Maze Hill",
    "DST":"Duke Street",
    "CSO":"Croston",
    "HTE":"Hatch End",
    "RDG":"Reading",
    "BRF":"Brierfield",
    "PFL":"Purfleet",
    "BPK":"Brookmans Park",
    "SKE":"Skewen",
    "CML":"Carmyle",
    "TRE":"Trefforest Estate",
    "UWL":"Upper Warlingham",
    "PRP":"Preston Park",
    "TTF":"Thetford",
    "GTR":"Goostrey",
    "BMH":"Bournemouth",
    "GOL":"Golspie",
    "PRA":"Prestwick International Airport",
    "SET":"Settle",
    "NRN":"Nairn",
    "BTG":"Barnt Green",
    "CNS":"Conisbrough",
    "DWD":"Dolwyddelan",
    "RKT":"Ruskington",
    "BTR":"Braintree",
    "NVR":"Navigation Road",
    "CSN":"Chessington North",
    "DRO":"Dronfield",
    "CRO":"Croy",
    "BHC":"Balloch",
    "BXH":"Bexleyheath",
    "POK":"Pokesdown",
    "SED":"Shelford (Cambs)",
    "LYP":"Lymington Pier",
    "RYE":"Rye (Sussex)",
    "SHP":"Shepperton",
    "MHS":"Meadowhall",
    "CMO":"Camelon",
    "BMC":"Bromley Cross (Lancs)",
    "WED":"Wedgwood",
    "MEL":"Meldreth",
    "EDN":"Eden Park",
    "EST":"Easterhouse",
    "SYL":"Syon Lane",
    "BGH":"Brighouse",
    "NGT":"Newington",
    "SFR":"Shalford (Surrey)",
    "CNR":"Crianlarich",
    "HIA":"Hampton-In-Arden",
    "GLT":"Glenrothes With Thornton",
    "RDN":"Reddish North",
    "NWT":"Newtown (Powys)",
    "LYC":"Lympstone Commando",
    "ADD":"Adderley Park",
    "DVY":"Dovey Junction",
    "ENT":"Entwistle",
    "BAK":"Battersea Park",
    "DIN":"Dingwall",
    "KDG":"Kidsgrove",
    "HUB":"Hunmanby",
    "TPC":"Thorpe Culvert",
    "PLG":"Polegate",
    "GOR":"Goring & Streatley",
    "COR":"Corby",
    "RTN":"Renton",
    "GLF":"Glenfinnan",
    "WSR":"Woodsmoor",
    "WTN":"Whitton (London)",
    "LWR":"Llanrwst",
    "ETC":"Etchingham",
    "ALR":"Alresford (Essex)",
    "SOV":"Southend Victoria",
    "BUY":"Burley Park",
    "LPT":"Longport",
    "GOO":"Goole",
    "HYS":"Hayes (Kent)",
    "TOL":"Tolworth",
    "CAK":"Cark & Cartmel",
    "SEC":"Seaton Carew",
    "ALV":"Alvechurch",
    "HGY":"Harringay",
    "DVH":"Dove Holes",
    "RRB":"Ryder Brow",
    "SMG":"St Margarets (London)",
    "LTV":"Lichfield Trent Valley",
    "PKG":"Penkridge",
    "HYR":"Haydons Road",
    "SRC":"Streatham Common",
    "LLR":"Llanharan",
    "LLI":"Llandybie",
    "BHG":"Bathgate",
    "ANC":"Ancaster",
    "LTH":"Llanhilleth",
    "TLH":"Tilehurst",
    "TBD":"Three Bridges",
    "MTG":"Mottingham",
    "CFF":"Croftfoot",
    "CHR":"Christchurch",
    "BXY":"Bexley",
    "HRR":"Harrington",
    "BCH":"Birchington-On-Sea",
    "CHD":"Chesterfield",
    "PMD":"Pembroke Dock",
    "HAP":"Hatfield Peverel",
    "OLF":"Oldfield Park",
    "LCL":"Lochailort",
    "AAP":"Alexandra Palace",
    "SLD":"Salford Crescent",
    "SBY":"Selby",
    "MKT":"Marks Tey",
    "BOT":"Bootle Oriel Road",
    "BIK":"Birkbeck",
    "GDP":"Gidea Park",
    "NWR":"Newtonmore",
    "WTM":"Witham",
    "DHM":"Durham",
    "SRT":"Shortlands",
    "LSW":"Leasowe",
    "LCC":"Lochluichart",
    "SCH":"Scotstounhill",
    "SHW":"Shawford",
    "BTY":"Bentley (Hants)",
    "DUD":"Duddeston",
    "SLV":"Silver Street",
    "DNS":"Dinas Powys",
    "HLB":"Hildenborough",
    "SDP":"Sandplace",
    "SLQ":"St Leonards Warrior Square",
    "NAN":"Nantwich",
    "CAO":"Cannock",
    "BAW":"Blackwater",
    "NIT":"Nitshill",
    "FRF":"Fairfield",
    "MFH":"Milford Haven",
    "HOW":"Howden",
    "CTW":"Church & Oswaldtwistle",
    "SLO":"Slough",
    "TON":"Tonbridge",
    "FCN":"Falconwood",
    "PTG":"Port Glasgow",
    "LAU":"Laurencekirk",
    "CKL":"Corkickle",
    "RMD":"Richmond (London)",
    "ADR":"Airdrie",
    "HBB":"Hubberts Bridge",
    "EPD":"Epsom Downs",
    "BRL":"Barrhill",
    "HON":"Honiton",
    "KLM":"Kilmaurs",
    "KPA":"Kensington Olympia",
    "BUL":"Butlers Lane",
    "AWT":"Armathwaite",
    "SOW":"Sowerby Bridge",
    "PKS":"Parkstone (Dorset)",
    "HSC":"Hoscar",
    "SRN":"Strines",
    "DKG":"Dorking (Main)",
    "COS":"Cosford",
    "AFS":"Ashford (Surrey)",
    "PHR":"Penshurst",
    "BAY":"Bayford",
    "GGJ":"Georgemas Junction",
    "FOC":"Falls Of Cruachan",
    "GNB":"Gainsborough Central",
    "KET":"Kettering",
    "STA":"Stafford",
    "WEE":"Weeley",
    "WBR":"Whaley Bridge",
    "RYH":"Rye House",
    "LNK":"Lanark",
    "LUX":"Luxulyan",
    "BGD":"Bargoed",
    "HAN":"Hanwell",
    "DMS":"Dormans",
    "BNW":"Bootle New Strand",
    "PIN":"Pinhoe",
    "PUR":"Purley",
    "HDG":"Heald Green",
    "URM":"Urmston",
    "HAB":"Habrough",
    "KGM":"Kingham",
    "WAF":"Wallyford",
    "BHO":"Blackhorse Road",
    "LCK":"Lockwood",
    "BML":"Bramhall",
    "BKQ":"Birkenhead Hamilton Square",
    "HEX":"Hexham",
    "CLI":"Clifton (Manchester)",
    "GVH":"Gravelly Hill",
    "LTN":"Luton Airport Parkway",
    "NTR":"Northallerton",
    "LEH":"Lea Hall",
    "WWD":"Woolwich Dockyard",
    "BFF":"Blaenau Ffestiniog",
    "VXH":"Vauxhall",
    "BRU":"Bruton",
    "TNS":"Thorne South",
    "FTW":"Fort William",
    "NUT":"Nutbourne",
    "OKL":"Oakleigh Park",
    "BEV":"Beverley",
    "KNE":"Kennett",
    "CHK":"Chiswick",
    "RAU":"Rauceby",
    "BLV":"Belle Vue",
    "HMW":"Hampton Wick",
    "EWR":"East Worthing",
    "GKW":"Greenock West",
    "WHE":"Whalley (Lancs)",
    "HDB":"Haydon Bridge",
    "CED":"Cheddington",
    "TRI":"Tring",
    "PBR":"Potters Bar",
    "GAR":"Garrowhill",
    "CHN":"Cheshunt",
    "EMP":"Emerson Park",
    "FOK":"Four Oaks",
    "LTM":"Lytham",
    "CLK":"Clock House",
    "AYS":"Aylesbury",
    "SVB":"Severn Beach",
    "LST":"Liverpool Street",
    "MTC":"Mitcham Eastfields",
    "PEA":"Peartree",
    "NET":"Netherfield",
    "NUF":"Nutfield",
    "KKH":"Kirkhill",
    "DUM":"Dumbreck",
    "SPF":"Springfield",
    "EDB":"Edinburgh",
    "SHI":"Shiplake",
    "ROG":"Rogart",
    "RET":"Retford",
    "AND":"Anderston",
    "SPR":"Springburn",
    "CMF":"Cromford",
    "GRL":"Greenfaulds",
    "MVL":"Malvern Link",
    "FLD":"Fauldhouse",
    "CBH":"Cambridge Heath",
    "SDF":"Saundersfoot",
    "SAN":"Sandown",
    "SNF":"Shenfield",
    "CBC":"Coatbridge Central",
    "BKT":"Blake Street",
    "MFL":"Mount Florida",
    "SDM":"Shieldmuir",
    "KBC":"Kinbrace",
    "ALO":"Alloa",
    "CMN":"Carmarthen",
    "DLG":"Dolgarrog",
    "NRB":"Norbury",
    "ZFD":"Farringdon",
    "CLV":"Claverdon",
    "HLS":"Hilsea",
    "BEH":"Bedworth",
    "CHC":"Charing Cross (Glasgow)",
    "DZY":"Danzey",
    "CSK":"Calstock",
    "TAP":"Taplow",
    "MTO":"Marton",
    "SHM":"Sheringham",
    "DBR":"Derby Road (Ipswich)",
    "CLN":"Chapeltown (South Yorks)",
    "SRA":"Stratford (London)",
    "EMD":"East Midlands Parkway",
    "KGT":"Kilgetty",
    "BFR":"London Blackfriars",
    "FOH":"Forest Hill",
    "TAF":"Taffs Well",
    "DHN":"Deighton",
    "GIP":"Gipsy Hill",
    "WAD":"Wadhurst",
    "MTN":"Moreton (Dorset)",
    "TRS":"Thurston",
    "NMP":"Northampton",
    "SDN":"St Denys",
    "BUT":"Burton-On-Trent",
    "NTB":"Norton Bridge",
    "ASC":"Ashchurch For Tewkesbury",
    "PER":"Penrhiwceiber",
    "GNL":"Green Lane",
    "STF":"Stromeferry",
    "YAL":"Yalding",
    "YSR":"Ystrad Rhondda",
    "WDL":"Woodhall",
    "GNF":"Greenfield",
    "HWD":"Hawarden",
    "HWY":"High Wycombe",
    "BRK":"Berwick (Sussex)",
    "TRR":"Torre",
    "KLD":"Kildale",
    "ULV":"Ulverston",
    "LVM":"Levenshulme",
    "DGC":"Denham Golf Club",
    "WRU":"West Ruislip",
    "FTN":"Fratton",
    "STP":"London St Pancras International",
    "WTA":"Wester Hailes",
    "BAA":"Barnham",
    "BAS":"Bere Alston",
    "AVM":"Aviemore",
    "CBE":"Canterbury East",
    "MLN":"Milngavie",
    "GOB":"Gobowen",
    "SLS":"Shettleston",
    "AFK":"Ashford International",
    "BTB":"Barnetby",
    "HMP":"Hampton (London)",
    "HLF":"Hillfoot",
    "SHU":"Stonehouse",
    "BLG":"Bellgrove",
    "LNW":"Llanwrtyd",
    "MKM":"Melksham",
    "WST":"Wood Street",
    "DRF":"Driffield",
    "SAS":"St Annes-On-Sea",
    "HUY":"Huyton",
    "MKR":"Market Rasen",
    "SOA":"Southampton Airport Parkway",
    "HCH":"Holmes Chapel",
    "FLN":"Flint",
    "AHD":"Ashtead",
    "YSM":"Ystrad Mynach",
    "CKN":"Crewkerne",
    "PLS":"Pleasington",
    "FXN":"Foxton",
    "BTD":"Bolton-On-Dearne",
    "ELP":"Ellesmere Port",
    "DAL":"Dalmally",
    "LSK":"Liskeard",
    "HKW":"Hackney Wick",
    "LIV":"Liverpool Lime Street",
    "CFH":"Chafford Hundred Lakeside",
    "RAY":"Raynes Park",
    "BER":"Bearley",
    "TOD":"Todmorden",
    "SYT":"Somerleyton",
    "MHR":"Market Harborough",
    "PEN":"Penarth",
    "ABW":"Abbey Wood",
    "CTO":"Carlton",
    "POO":"Poole",
    "KNF":"Knutsford",
    "WND":"Wendover",
    "ARB":"Arbroath",
    "NTL":"Netley",
    "BKC":"Birkenhead Central",
    "CRT":"Chartham",
    "AVP":"Aylesbury Vale Parkway",
    "BNM":"Burnham (Bucks)",
    "MAS":"Manors",
    "BAC":"Bache",
    "ETL":"East Tilbury",
    "INS":"Insch",
    "DRT":"Darton",
    "CFD":"Castleford",
    "WNL":"Whinhill",
    "SAE":"Saltaire",
    "CNN":"Canonbury",
    "AUD":"Audley End",
    "WOO":"Wool",
    "RIS":"Rishton",
    "CLY":"Chinley",
    "BSI":"Balmossie",
    "BIW":"Biggleswade",
    "NTC":"Newton St Cyres",
    "BLT":"Blantyre",
    "SFA":"Stratford International",
    "LSY":"Lower Sydenham",
    "LAP":"Lapford",
    "BEC":"Beckenham Hill",
    "SDY":"Sandy",
    "CAR":"Carlisle",
    "BYK":"Bentley (South Yorks)",
    "CUD":"Cuddington",
    "BKS":"Bekesbourne",
    "PUL":"Pulborough",
    "KKB":"Kirkby-In-Ashfield",
    "ERL":"Earlestown",
    "BCB":"Burscough Bridge",
    "SST":"Stansted Mountfitchet",
    "EGT":"Egton",
    "PSC":"Prescot",
    "WLW":"Welwyn North",
    "KGE":"Kingsknowe",
    "THI":"Thirsk",
    "WYM":"Wylam",
    "GMB":"Grimsby Town",
    "LNR":"Llanwrda",
    "SRY":"Shoeburyness",
    "WCK":"Wick",
    "DWN":"Darwen",
    "STD":"Stroud (Gloucs)",
    "TUH":"Tulse Hill",
    "LEM":"Leyton Midland Road",
    "LWH":"Lawrence Hill",
    "MCE":"Metrocentre",
    "THO":"Thornford",
    "BEX":"Bexhill",
    "EGG":"Eggesford",
    "AHV":"Ash Vale",
    "KNL":"Kensal Green",
    "CFB":"Catford Bridge",
    "BOD":"Bodmin Parkway",
    "AYW":"Aberystwyth",
    "BYE":"Bynea",
    "AMB":"Ambergate",
    "KKM":"Kirkham & Wesham",
    "BPS":"Blackpool South",
    "YRK":"York",
    "FRT":"Frant",
    "DNY":"Danby",
    "IGD":"Invergordon",
    "TLS":"Thorpe-Le-Soken",
    "CTM":"Chatham",
    "KEH":"Keith",
    "GMD":"Grimsby Docks",
    "SNL":"Stoneleigh",
    "BRV":"Bournville",
    "RED":"Redruth",
    "CHL":"Chilworth",
    "BKN":"Birkenhead North",
    "WAT":"Waterloo",
    "MTL":"Mortlake",
    "INP":"Inverkip",
    "SWI":"Swindon (Wilts)",
    "PCD":"Pencoed",
    "BKW":"Berkswell",
    "AWM":"Ashwell & Morden",
    "BDA":"Brundall",
    "ELD":"Earlswood (Surrey)",
    "HEC":"Heckington",
    "HTC":"Heaton Chapel",
    "LAI":"Laindon",
    "NQY":"Newquay",
    "FEN":"Fenny Stratford",
    "PYL":"Pyle",
    "CMR":"Cromer",
    "ILK":"Ilkley",
    "SEE":"Southease",
    "CPK":"Carpenders Park",
    "PLD":"Portslade",
    "EPH":"Elephant & Castle",
    "BYC":"Betws-Y-Coed",
    "BID":"Bidston",
    "AIR":"Airbles",
    "CHI":"Chingford",
    "ARR":"Arram",
    "WKD":"Walkden",
    "WHY":"Whyteleafe",
    "BFR":"Blackfriars",
    "WHA":"Westenhanger",
    "SEL":"Sellafield",
    "BKJ":"Beckenham Junction",
    "WDM":"Windermere",
    "FRB":"Fairbourne",
    "WKI":"West Kirby",
    "ALM":"Alnmouth",
    "DDK":"Dagenham Dock",
    "GMG":"Garth (Bridgend)",
    "HDE":"Hedge End",
    "UTT":"Uttoxeter",
    "CWN":"Cowden (Kent)",
    "FKK":"Falkirk High",
    "MDG":"Midgham",
    "STN":"Stonehaven",
    "ROC":"Roche",
    "BLN":"Blundellsands & Crosby",
    "KWB":"Kew Bridge",
    "BCY":"Brockley",
    "BYF":"Broughty Ferry",
    "SCT":"Scotscalder",
    "BCF":"Beaconsfield",
    "SCA":"Scarborough",
    "EGN":"Eastrington",
    "CDN":"Coulsdon Town",
    "CWH":"Crews Hill",
    "KYL":"Kyle Of Lochalsh",
    "MGM":"Metheringham",
    "TQY":"Torquay",
    "NHE":"New Hythe",
    "GDL":"Godley",
    "GBL":"Gainsborough Lea Road",
    "TYC":"Ty Croes",
    "ASP":"Aspatria",
    "COW":"Cowdenbeath",
    "BUJ":"Burton Joyce",
    "SLH":"Sleights",
    "BAL":"Balham",
    "PNL":"Pannal",
    "HYL":"Hayle",
    "FLW":"Fulwell",
    "BSD":"Bearsted",
    "RDA":"Redland",
    "DOL":"Dolau",
    "LAM":"Lamphey",
    "CNE":"Colne",
    "PTD":"Pontarddulais",
    "DVC":"Dovercourt",
    "HNF":"Hednesford",
    "VAL":"Valley",
    "CPY":"Clapham (North Yorkshire)",
    "BMN":"Bromley North",
    "BFD":"Brentford",
    "DOD":"Dodworth",
    "HAD":"Haddiscoe",
    "WFH":"Watford High Street",
    "ANL":"Anniesland",
    "GYP":"Gypsy Lane",
    "DGY":"Deganwy",
    "CEY":"Cononley",
    "TYS":"Tyseley",
    "CLL":"Collington",
    "SEG":"Selling",
    "KIV":"Kiveton Bridge",
    "DSY":"Daisy Hill",
    "HLU":"Helensburgh Upper",
    "HER":"Hersham",
    "DLW":"Dalwhinnie",
    "PMS":"Portsmouth & Southsea",
    "WAE":"London Waterloo East",
    "WTR":"Wateringbury",
    "BSJ":"Bedford St Johns",
    "DBD":"Denby Dale",
    "NDL":"North Dulwich",
    "LOH":"Lostock Hall",
    "PLW":"Pollokshields West",
    "MNG":"Manningtree",
    "YNW":"Ynyswen",
    "STE":"Streatham(Greater London)",
    "ALN":"Althorne (Essex)",
    "LOS":"Lostwithiel",
    "KND":"Kingswood",
    "SLT":"Saltcoats",
    "MOB":"Mobberley",
    "FRE":"Freshfield",
    "SHH":"Shirehampton",
    "RAI":"Rainham (Kent)",
    "NCK":"New Cumnock",
    "HRN":"Hornsey",
    "WLN":"Wellington (Shropshire)",
    "WRN":"West Runton",
    "CHX":"London Charing Cross",
    "GSC":"Gilshochill",
    "MUB":"Musselburgh",
    "SVK":"Seven Kings",
    "SCY":"South Croydon",
    "SAJ":"St Johns (London)",
    "ELS":"Elstree & Borehamwood",
    "NFD":"Northfield",
    "ACN":"Achnasheen",
    "AON":"Alton",
    "BCC":"Beccles",
    "BKH":"Blackheath",
    "LBG":"London Bridge",
    "RMF":"Romford",
    "CLM":"Collingham",
    "TLK":"The Lakes (Warks)",
    "SAF":"Salfords (Surrey)",
    "SMH":"Stamford Hill",
    "LHD":"Leatherhead",
    "BCV":"Bruce Grove",
    "CHP":"Chipstead",
    "THD":"Thames Ditton",
    "WTI":"Winnersh Triangle",
    "KGS":"Kings Sutton",
    "HDF":"Hadfield",
    "TMC":"Templecombe",
    "PMB":"Pembroke",
    "MRP":"Moorthorpe",
    "WSU":"West Sutton",
    "BRT":"Barlaston",
    "MDW":"Maidstone West",
    "GLY":"Glynde",
    "GDN":"Godstone",
    "DNO":"Dunrobin Castle",
    "AGV":"Abergavenny",
    "FLX":"Felixstowe",
    "WTT":"Witton (West Midlands)",
    "DNT":"Dent",
    "LLF":"Llanfairfechan",
    "BSC":"Bescot Stadium",
    "KWG":"Kew Gardens",
    "TWY":"Twyford",
    "WCY":"West Croydon",
    "ASK":"Askam",
    "LNY":"Langley (Berks)",
    "WON":"Walton-On-The-Naze",
    "HTH":"Handforth",
    "CWE":"Crowle",
    "RDW":"Reading West",
    "LEI":"Leicester",
    "TFC":"Telford Central",
    "BPB":"Blackpool Pleasure Beach",
    "HPL":"Hartlepool",
    "GFD":"Greenford",
    "MRS":"Monks Risborough",
    "SMR":"Smethwick Rolfe Street",
    "EML":"East Malling",
    "LBZ":"Leighton Buzzard",
    "CHE":"Cheam",
    "EBN":"Eastbourne",
    "BDH":"Bedhampton",
    "KTL":"Kirton Lindsey",
    "BOH":"Bosham",
    "DEE":"Dundee",
    "LGG":"Langley Green",
    "ALP":"Althorpe",
    "ORP":"Orpington",
    "EXT":"Exeter St Thomas",
    "EDL":"Edale",
    "LTK":"Little Kimble",
    "KKS":"Kirk Sandall",
    "CYN":"Cynghordy",
    "BGG":"Brigg",
    "BPT":"Bishopton (Strathclyde)",
    "CLH":"Clitheroe",
    "DCG":"Duncraig",
    "NLN":"New Lane",
    "GLS":"Glaisdale",
    "GVE":"Garve",
    "WVF":"Wivelsfield",
    "DMP":"Dumpton Park",
    "HSL":"Haslemere",
    "HIG":"Highbridge & Burnham",
    "GNH":"Greenhithe",
    "SNS":"Staines",
    "NTH":"Neath",
    "MUF":"Manchester United Football Ground",
    "HDL":"Headstone Lane",
    "BKO":"Brookwood",
    "HRO":"Harold Wood",
    "KMK":"Kilmarnock",
    "HSD":"Hamstead (Birmingham)",
    "CPM":"Chippenham",
    "WAL":"Walton-On-Thames",
    "RCE":"Redcar East",
    "FKW":"Folkestone West",
    "ERD":"Erdington",
    "CIM":"Cilmeri",
    "AML":"Acton Main Line",
    "MRY":"Maryport",
    "TRB":"Treherbert",
    "DKD":"Dunkeld & Birnam",
    "CPU":"Capenhurst",
    "EBT":"Edenbridge Town",
    "BRC":"Breich",
    "PWE":"Pollokshaws East",
    "LNG":"Longcross",
    "REC":"Rectory Road",
    "WSE":"Winchelsea",
    "LBT":"Larbert",
    "RBS":"Redcar British Steel",
    "LEA":"Leagrave",
    "CKY":"Crosskeys",
    "BYA":"Berney Arms",
    "PEW":"Pewsey",
    "CTT":"Church Stretton",
    "TIR":"Tir-Phil",
    "HGD":"Hungerford",
    "CTL":"Cattal",
    "SGN":"South Greenford",
    "TNN":"Thorne North",
    "TIL":"Tilbury Town",
    "GWE":"Gwersyllt",
    "HIR":"Horton-In-Ribblesdale",
    "BSY":"Brondesbury",
    "CLU":"Carluke",
    "PMP":"Plumpton",
    "DCT":"Danescourt",
    "ALF":"Alfreton",
    "BRX":"Brixton",
    "ADV":"Andover",
    "ERA":"Eastham Rake",
    "SHJ":"St Helens Junction",
    "KLY":"Kenley",
    "HFD":"Hereford",
    "PTK":"Partick",
    "HDY":"Headingley",
    "CBR":"Cooksbridge",
    "DON":"Doncaster",
    "WKK":"Wakefield Kirkgate",
    "HOR":"Horley",
    "WTH":"Whitehaven",
    "SAB":"Smallbrook Junction",
    "BOM":"Bromborough",
    "NMC":"New Mills Central",
    "HWM":"Harlow Mill",
    "CUW":"Clunderwen",
    "RCC":"Redcar Central",
    "EDW":"East Dulwich",
    "LEW":"Lewisham",
    "HYB":"Honeybourne",
    "HEL":"Hensall",
    "BLL":"Bardon Mill",
    "DFD":"Dartford",
    "FNB":"Farnborough (Main)",
    "HLG":"Hall Green",
    "HGN":"Hough Green",
    "FNT":"Feniton",
    "HLL":"Heath Low Level",
    "GMV":"Great Malvern",
    "OLY":"Ockley",
    "BRE":"Brentwood",
    "PPK":"Possilpark & Parkhouse",
    "BHM":"Birmingham New Street",
    "TEN":"Tenby",
    "SNT":"Stanlow & Thornton",
    "MAN":"Manchester Piccadilly",
    "IVY":"Ivybridge",
    "PYN":"Penryn (Cornwall)",
    "WCL":"West Calder",
    "TEO":"Theobalds Grove",
    "CMY":"Crossmyloof",
    "HVN":"Havenhouse",
    "WBP":"West Brompton",
    "SDB":"Sandbach",
    "PAD":"Paddington",
    "SEN":"Shenstone",
    "FLT":"Flitwick",
    "RUG":"Rugby",
    "YAE":"Yate",
    "AYL":"Aylesford",
    "TAD":"Tadworth",
    "MLH":"Mill Hill (Lancs)",
    "ROE":"Rotherhithe",
    "WME":"Woodmansterne",
    "TOT":"Totnes",
    "GIG":"Giggleswick",
    "HXM":"Hoveton & Wroxham",
    "HRH":"Horsham",
    "DNG":"Dunton Green",
    "SIT":"Sittingbourne",
    "SYB":"Stalybridge",
    "WLG":"Wallasey Grove Road",
    "HND":"Hanborough",
    "MRD":"Morchard Road",
    "KIN":"Kingussie",
    "BAD":"Banstead",
    "EUS":"Euston",
    "BNH":"Barnehurst",
    "NBR":"Narborough",
    "SIA":"Southend Airport",
    "MCO":"Manchester Oxford Road",
    "LRG":"Lairg",
    "PRE":"Preston (Lancs)",
    "LYE":"Lye (West Midlands)",
    "CDQ":"Cardiff Queen Street",
    "LAY":"Layton (Lancs)",
    "HXX":"Heathrow Airport Terminals 1, 2 And 3",
    "NWP":"Newport (South Wales)",
    "NVN":"Newhaven Town",
    "DRI":"Drigg",
    "BSU":"Brunstane",
    "WBD":"Whitley Bridge",
    "LGS":"Langside",
    "SDA":"Snodland",
    "LHM":"Lealholm",
    "OKE":"Okehampton",
    "KDY":"Kirkcaldy",
    "WHI":"Whitstable",
    "BRY":"Barry",
    "SIH":"St Helier (Surrey)",
    "ATB":"Attenborough",
    "ORN":"Old Roan",
    "CLR":"Clarbeston Road",
    "BDL":"Birkdale",
    "CPW":"Chepstow",
    "QBR":"Queenborough",
    "MSW":"Mansfield Woodhouse",
    "FNW":"Farnworth",
    "BUE":"Bures",
    "SXY":"Saxilby",
    "BNF":"Briton Ferry",
    "GOF":"Golf Street",
    "PTA":"Port Talbot Parkway",
    "NAY":"Newton Aycliffe",
    "APF":"Appleford",
    "TYL":"Tyndrum Lower",
    "GRA":"Grantham",
    "BMG":"Barming",
    "GRP":"Grove Park",
    "CPN":"Chapelton (Devon)",
    "FFA":"Ffairfach",
    "BDB":"Broadbottom",
    "BVD":"Belvedere",
    "BNV":"Banavie",
    "ARU":"Arundel",
    "JEQ":"Jewellery Quarter",
    "SNG":"Sunningdale",
    "MTM":"Martin Mill",
    "PGM":"Pengam",
    "GSN":"Garston (Hertfordshire)",
    "NEI":"Neilston",
    "HIP":"Highams Park",
    "YEO":"Yeoford",
    "PYT":"Poynton",
    "ARN":"Arnside",
    "BDI":"Bradford Interchange",
    "SNY":"Sunnymeads",
    "BMB":"Bamber Bridge",
    "WMN":"Warminster",
    "VIC":"London Victoria",
    "WMS":"Wemyss Bay",
    "DDP":"Dudley Port",
    "IVR":"Iver",
    "BLH":"Bellshill",
    "KIL":"Kildonan",
    "GFF":"Gilfach Fargoed",
    "BFN":"Byfleet & New Haw",
    "BIA":"Bishop Auckland",
    "SKW":"Stoke Newington",
    "THU":"Thurgarton",
    "DUR":"Durrington-On-Sea",
    "RWC":"Rawcliffe",
    "WOS":"Worcester Shrub Hill",
    "ELG":"Elgin",
    "WNW":"West Norwood",
    "STY":"Stratford-Upon-Avon Parkway",
    "HIB":"High Brooms",
    "BEN":"Bentham",
    "WHT":"Whitchurch (Cardiff)",
    "BCS":"Bicester North",
    "PAN":"Pangbourne",
    "LWT":"Lowestoft",
    "CNM":"Cheltenham Spa",
    "LHW":"Lochwinnoch",
    "DFP":"Dublin Ferryport",
    "GSD":"Garsdale",
    "WFF":"Whifflet",
    "MLF":"Milford (Surrey)",
    "INK":"Inverkeithing",
    "SUP":"Sundridge Park",
    "COE":"Coombe Junction Halt",
    "MSS":"Moses Gate",
    "FOG":"Forest Gate",
    "FEL":"Feltham",
    "PDG":"Padgate",
    "PAR":"Par",
    "BSO":"Basildon",
    "PCN":"Paisley Canal",
    "BIO":"Baillieston",
    "LLG":"Llangadog",
    "SND":"Sandhurst (Berks)",
    "UPH":"Upper Halliford",
    "RUF":"Rufford",
    "PSH":"Pershore",
    "SBE":"Starbeck",
    "EWW":"Ewell West",
    "CFT":"Crofton Park",
    "WRS":"Wressle",
    "DMG":"Dinas (Rhondda)",
    "BGE":"Broad Green",
    "TAT":"Tattenham Corner",
    "WNG":"Waun-Gron Park",
    "DAM":"Dalmeny",
    "BUU":"Burnham-On-Crouch",
    "BOA":"Bradford-On-Avon",
    "WIM":"Wimbledon",
    "BIF":"Barrow-In-Furness",
    "WDH":"Woodhouse",
    "WWI":"West Wickham",
    "BET":"Bethnal Green",
    "WOB":"Woburn Sands",
    "MCV":"Manchester Victoria",
    "RYB":"Roy Bridge",
    "KNS":"Kennishead",
    "SUU":"Sunbury",
    "PSE":"Pitsea",
    "NRC":"Newbury Racecourse",
    "SMO":"South Merton",
    "LAG":"Langwith-Whaley Thorns",
    "GBD":"Gilberdyke",
    "WDT":"West Drayton",
    "HSW":"Heswall",
    "HNL":"Henley-In-Arden",
    "SRU":"South Ruislip",
    "ASY":"Ashley",
    "BSK":"Basingstoke",
    "HDM":"Haddenham & Thame Parkway",
    "LAW":"Landywood",
    "SSS":"Sheerness-On-Sea",
    "ADW":"Addiewell",
    "CDY":"Cartsdyke",
    "RNM":"Rainham (Essex)",
    "LGK":"Longbeck",
    "CHF":"Church Fenton",
    "OUS":"Oulton Broad South",
    "RIL":"Rice Lane",
    "SKN":"St Keyne Wishing Well Halt",
    "MAY":"Maybole",
    "SWK":"Southwick",
    "KNA":"Knaresborough",
    "BRM":"Barmouth",
    "LWS":"Lewes",
    "SWD":"Swinderby",
    "CHG":"Charing (Kent)",
    "CDU":"Cam & Dursley",
    "MLG":"Mallaig",
    "BKG":"Barking",
    "TAM":"Tamworth",
    "LPG":"Llanfairpwll",
    "HHY":"Highbury & Islington",
    "HLE":"Hillington East",
    "PSW":"Polesworth",
    "TIP":"Tipton",
    "WHD":"West Hampstead",
    "LVG":"Livingston South",
    "BYD":"Barry Docks",
    "WNH":"Warnham",
    "MMO":"Melton Mowbray",
    "CDO":"Cardonald",
    "ACT":"Ascot (Berks)",
    "SGM":"St Germans",
    "PNM":"Penmere",
    "BLP":"Belper",
    "COL":"Colchester",
    "SNA":"Sandal & Agbrigg",
    "LAS":"Llansamlet",
    "SEV":"Sevenoaks",
    "NNT":"Nunthorpe",
    "SUN":"Sunderland",
    "HYM":"Haymarket",
    "HRW":"Harrow & Wealdstone",
    "BYN":"Bryn",
    "WIN":"Winchester",
    "LBK":"Long Buckby",
    "WLS":"Woolston",
    "HGG":"Haggerston",
    "SKI":"Skipton",
    "RHD":"Ribblehead",
    "BUC":"Buckenham (Norfolk)",
    "WEM":"Wem",
    "CRM":"Cramlington",
    "GTW":"Gatwick Airport",
    "FRW":"Fairwater",
    "PTH":"Perth",
    "BUX":"Buxton",
    "NBE":"Newbridge",
    "CDF":"Cardiff Central",
    "COA":"Coatdyke",
    "STV":"Stevenston",
    "BHI":"Birmingham International",
    "SNI":"Snaith",
    "HYN":"Hyndland",
    "CBY":"Charlbury",
    "AFV":"Ansdell & Fairhaven",
    "MTH":"Motherwell",
    "BAV":"Barrow Haven",
    "WAS":"Watton-At-Stone",
    "ERH":"Erith",
    "BAH":"Bank Hall",
    "NHL":"New Holland",
    "BBG":"Bishopbriggs",
    "HYK":"Hoylake",
    "HLC":"Helensburgh Central",
    "CTF":"Catford",
    "ENC":"Enfield Chase",
    "CLT":"Clacton-On-Sea",
    "KIR":"Kirkby (Merseyside)",
    "CLS":"Chester-Le-Street",
    "LYM":"Lympstone Village",
    "NFN":"Nafferton",
    "FSK":"Fiskerton",
    "KID":"Kidderminster",
    "LND":"Longniddry",
    "RCD":"Rochdale",
    "DMK":"Denmark Hill",
    "OXS":"Oxshott",
    "LCS":"Locheilside",
    "WRH":"Worthing",
    "HSY":"Horsley",
    "CRW":"Crawley",
    "CON":"Connel Ferry",
    "GTN":"Grangetown (Cardiff)",
    "MEY":"Merryton",
    "PNA":"Penally",
    "BOC":"Bootle (Cumbria)",
    "HOO":"Hooton",
    "MIM":"Moreton-In-Marsh",
    "PTF":"Pantyffynnon",
    "WIV":"Wivenhoe",
    "PRW":"Perranwell",
    "LFD":"Lingfield",
    "WES":"Westerton",
    "BAB":"Balcombe",
    "PDW":"Paddock Wood",
    "YVP":"Yeovil Pen Mill",
    "CRF":"Carfin",
    "FNY":"Finchley Road & Frognal",
    "GTA":"Great Ayton",
    "SMY":"St Mary Cray",
    "PWL":"Pwllheli",
    "BEY":"Ben Rhydding",
    "CGN":"Cogan",
    "PIL":"Pilning",
    "SOM":"South Milford",
    "TPN":"Ton Pentre",
    "SWR":"Stewartby",
    "TRU":"Truro",
    "HOY":"Honley",
    "HFX":"Halifax",
    "KLN":"Kings Lynn",
    "GMY":"Goodmayes",
    "MCM":"Morecambe",
    "MAO":"Martins Heron",
    "COM":"Commondale",
    "DUN":"Dunbar",
    "QRP":"Queens Road (Peckham)",
    "SHO":"Sholing",
    "WGC":"Welwyn Garden City",
    "BRP":"Brampton (Suffolk)",
    "CEH":"Coleshill Parkway",
    "WWO":"West Worthing",
    "BGA":"Brundall Gardens",
    "DWW":"Dawlish Warren",
    "WMC":"Wilmcote",
    "STR":"Stranraer",
    "SNN":"Swinton (Manchester)",
    "SHN":"Shanklin",
    "DMR":"Dalmuir",
    "BRS":"Berrylands",
    "CDD":"Cardenden",
    "MAX":"Maxwell Park",
    "SRS":"Selhurst",
    "MSD":"Moorside",
    "SNR":"Sanderstead",
    "BEM":"Bempton",
    "MIH":"Mills Hill (Manchester)",
    "AWK":"Adwick",
    "WOR":"Worle",
    "YET":"Yetminster",
    "OKM":"Oakham",
    "BWG":"Bowling",
    "SIE":"Sherburn-In-Elmet",
    "OKN":"Oakengates",
    "HIN":"Hindley",
    "WMB":"Wembley Central",
    "PRB":"Prestbury",
    "CDS":"Coulsdon South",
    "PRY":"Perry Barr",
    "APP":"Appleby",
    "SRR":"Sarn",
    "CNO":"Chetnole",
    "MRT":"Moreton (Merseyside)",
    "WWW":"Wootton Wawen",
    "LPW":"Lapworth",
    "MEX":"Mexborough",
    "GMT":"Grosmont",
    "DSM":"Darsham",
    "RDS":"Reddish South",
    "BLD":"Baildon",
    "WNS":"Winnersh",
    "BIC":"Billericay",
    "GOD":"Godalming",
    "WRX":"Wrexham General",
    "AAT":"Achanalt",
    "HWI":"Horwich Parkway",
    "CYP":"Crystal Palace",
    "PRS":"Prees",
    "WCP":"Worcester Park",
    "CAT":"Caterham",
    "KIT":"Kintbury",
    "GWN":"Gowerton",
    "ATL":"Attleborough",
    "MON":"Monifieth",
    "WCR":"Whitecraigs",
    "SEF":"Seaford (Sussex)",
    "NNG":"Newark North Gate",
    "OMS":"Ormskirk",
    "BAR":"Bare Lane",
    "BNY":"Barnsley",
    "HPE":"Hope (Flintshire)",
    "BGL":"Bugle",
    "CBG":"Cambridge",
    "GKC":"Greenock Central",
    "LTS":"Lelant Saltings",
    "LAK":"Lakenheath",
    "PNW":"Penge West",
    "WYB":"Weybridge",
    "WTB":"Whitby",
    "BGS":"Bogston",
    "KEM":"Kemble",
    "PET":"Petts Wood",
    "KEL":"Kelvedon",
    "FBY":"Formby",
    "COO":"Cookham",
    "MEV":"Merthyr Vale",
    "WDE":"Wood End",
    "BEB":"Bebington",
    "BUI":"Burnside (Strathclyde)",
    "CCC":"Criccieth",
    "TRA":"Trafford Park",
    "RUT":"Rutherglen",
    "NXG":"New Cross Gate",
    "CDB":"Cardiff Bay",
    "SMD":"Stamford (Lincs)",
    "BNA":"Burnage",
    "RDC":"Redditch",
    "WRE":"Wrenbury",
    "MSR":"Minster",
    "POP":"Poppleton",
    "BSW":"Birmingham Snow Hill",
    "PBO":"Peterborough",
    "HWW":"How Wood (Herts)",
    "MEN":"Menheniot",
    "SMB":"Smithy Bridge",
    "CWS":"Caersws",
    "HPD":"Harpenden",
    "HNC":"Hamilton Central",
    "LET":"Letchworth Garden City",
    "SBV":"St Budeaux Victoria Road",
    "RNH":"Rainhill",
    "SAM":"Saltmarshe",
    "DPT":"Devonport (Devon)",
    "BXW":"Box Hill & Westhumble",
    "ACH":"Achnashellach",
    "DOC":"Devonport Dockyard",
    "IMW":"Imperial Wharf",
    "SVS":"Seven Sisters",
    "NQU":"North Queensferry",
    "SAV":"Stratford-Upon-Avon",
    "BMY":"Bramley (Hants)",
    "PAD":"London Paddington",
    "LDY":"Ladybank",
    "GSL":"Gunnislake",
    "CAG":"Carrbridge",
    "ORR":"Orrell",
    "EAR":"Earley",
    "HOH":"Harrow-On-The-Hill",
    "ADM":"Adisham",
    "WGW":"Wigan Wallgate",
    "MTS":"Montrose",
    "BWD":"Birchwood",
    "LUD":"Ludlow",
    "WOL":"Wolverton",
    "SWA":"Swansea",
    "HFE":"Hertford East",
    "ESW":"Elmswell",
    "NRT":"Nethertown",
    "CKH":"Corkerhill",
    "KWN":"Kilwinning",
    "PAL":"Palmers Green",
    "LGW":"Langwathby",
    "BLW":"Bulwell",
    "STJ":"Severn Tunnel Junction",
    "RLN":"Rowlands Castle",
    "SUG":"Sugar Loaf",
    "GLG":"Glengarnock",
    "SQH":"Sanquhar",
    "CSR":"Chassen Road",
    "FFD":"Freshford",
    "SPN":"Spooner Row",
    "DTW":"Droitwich Spa",
    "KNR":"Kensal Rise",
    "KNG":"Kingston",
    "CLA":"Clandon",
    "BMD":"Brimsdown",
    "THS":"Thurso",
    "EVE":"Evesham",
    "ERI":"Eridge",
    "KNO":"Knottingley",
    "HWH":"Haltwhistle",
    "SQU":"Squires Gate",
    "DTG":"Dinting",
    "FLM":"Flimby",
    "LRD":"London Road (Guildford)",
    "HES":"Hessle",
    "EGF":"East Garforth",
    "ACL":"Acle",
    "SRI":"Spring Road",
    "WKB":"West Kilbride",
    "BCU":"Brockenhurst",
    "MOR":"Mortimer",
    "PFY":"Poulton-Le-Fylde",
    "GLH":"Glasshoughton",
    "GOX":"Goxhill",
    "TVP":"Tiverton Parkway",
    "SPY":"Shepley",
    "CYK":"Clydebank",
    "NEH":"New Eltham",
    "SBT":"Stourbridge Town",
    "MSK":"Marske",
    "SAX":"Saxmundham",
    "ASF":"Ashfield",
    "GYM":"Great Yarmouth",
    "SOH":"South Hampstead",
    "CLJ":"Clapham Junction",
    "WGR":"Woodgrange Park",
    "KMS":"Kemsing",
    "WNR":"Windsor & Eton Riverside",
    "CCH":"Chichester",
    "WMD":"Wymondham",
    "BAU":"Barton-On-Humber",
    "AUG":"Aughton Park",
    "HVF":"Haverfordwest",
    "SFN":"Shifnal",
    "SRL":"Shirley",
    "WHM":"Whimple",
    "KWD":"Kirkwood",
    "GTY":"Gatley",
    "POT":"Pontefract Tanshelf",
    "SIV":"St Ives (Cornwall)",
    "GLD":"Guildford",
    "BEA":"Bridge Of Allan",
    "BEL":"Beauly",
    "QYD":"Quakers Yard",
    "CLC":"Castle Cary",
    "HDN":"Harlesden",
    "RDH":"Redhill",
    "PKT":"Park Street",
    "IPS":"Ipswich",
    "TEA":"Tees-Side Airport",
    "SHD":"Shildon",
    "LLS":"Llanishen",
    "WSF":"Winsford",
    "EAG":"Eaglescliffe",
    "LRB":"London Road (Brighton)",
    "RFD":"Rochford",
    "NEL":"Nelson",
    "HAV":"Havant",
    "HME":"Hamble",
    "PSN":"Parson Street",
    "WAT":"London Waterloo",
    "OCK":"Ockendon",
    "BON":"Bolton",
    "MER":"Merthyr Tydfil",
    "WLE":"Whittlesea",
    "WDU":"West Dulwich"
};